### ISSUE TITLE
Decide on Styling

### ISSUE THREAD

**Issue by magmesser** [magmesser/georgia-evergreens#26]
CSS Styling
Instead of using a CSS library like Bootstrap, consider one of the following suggestions:

Explore the concept of CSS-in-JS, which abstracts CSS to the component level, using JavaScript to describe styles in a declarative and maintainable way. Some popular libraries include [styled-componentsLinks to an external site.](https://styled-components.com/) and [EmotionLinks to an external site.](https://emotion.sh/docs/introduction).

Try using a component library, such as [Semantic UILinks to an external site.](https://semantic-ui.com/), [Chakra UILinks to an external site.](https://chakra-ui.com/), or [Ant DesignLinks to an external site.](https://ant.design/).

Create all the CSS for your application just using CSS.

**Comment by laps22** [comment]
![AdobeColor-Real Noni](https://user-images.githubusercontent.com/113871469/225485147-1a9c0dfc-7b2f-40dd-a24f-42aa6b557407.jpeg)

**Comment by laps22** [comment]
Tailwinds and Vite for CSS framework/React Front End package
